version: '3'

services:

  postgres:
    container_name: shortener-postgres
    image: postgres
    environment:
      POSTGRES_USER: bale
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: bale.postgres.ir!

    ports:
      - 5432:5432
    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data
    restart: always