version: '3'

services:

  postgres:
    container_name: shortener-postgres
    image: postgres
    environment:
      POSTGRES_USER: bale
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: bale.postgres.ir!

    ports:
      - 5432:5432
    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: shortener-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=bale.redis.ir!

    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ../../../redis.conf:/usr/local/etc/redis/redis.conf